# Generated by Django 3.0.3 on 2020-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, to='street.Like'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, to='street.Like'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='street.Tag'),
        ),
    ]
